INSERT INTO CLIENT(NAME, EMAIL, CREATED_AT, BALANCE) VALUES ('cliente 1', 'ciente@hotmail.com', CURRENT_TIMESTAMP(), 1000);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (100, CURRENT_TIMESTAMP(),  'DESCRIPTION', CURRENT_TIMESTAMP() , 1, 0, 0, null, 1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (150, CURRENT_TIMESTAMP(),  'DESCRIPTION', CURRENT_TIMESTAMP() , 2, 1, 1, null, 1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (200, CURRENT_TIMESTAMP(),  'DESCRIPTION', CURRENT_TIMESTAMP() , 3, 1, 0, 3, 1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (100, CURRENT_TIMESTAMP(),  'DESCRIPTION', CURRENT_TIMESTAMP() , 1, 0, 0, 2, 1);
