INSERT INTO client (name, email, created_at, password, password_verification, role)
VALUES ('Fulano', 'fulano@example.com', CURRENT_TIMESTAMP(),
        '$2a$10$qvkN2RGg1mg8IOlwWWuOnunwtMfWTGBXY5usiFJa5UJ.JVqWxYYim', 'Ul9UnIc9V5hejN/PFg3yo2Un/+mk0SKT', 'USER');

INSERT INTO division(NAME, TYPE, CATEGORY, CREATED_AT)
VALUES ('Saude', 'HEALTH', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Casa', 'HOME', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Eletrônico', 'ELECTRONIC', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Restaurante', 'RESTAURANT', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Academia', 'GYM', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Aluguel', 'RENT', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Supermercado', 'MARKET', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Lazer', 'LEISURE', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Combustivel', 'FUEL', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Delivery', 'DELIVERY', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('BadBet', 'BAD_BET', 'EXPENSE', CURRENT_TIMESTAMP()),
       ('Salário', 'SALARY', 'INCOME', CURRENT_TIMESTAMP()),
       ('Bônus', 'BONUS', 'INCOME', CURRENT_TIMESTAMP()),
       ('GoodBet', 'GOOD_BET', 'INCOME', CURRENT_TIMESTAMP()),
       ('Investimento', 'INVESTMENT', 'INCOME', CURRENT_TIMESTAMP());


INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (2500, '2023-06-01', 'Salário', '2023-06-05', 'NOT_RECEIVED', 'INCOME', 'FIX', true, null, 1, 12);

INSERT INTO FIX_TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, EDITED, DIVISION_ID, TRANSACTION_ID,
                            CATEGORY)
VALUES (2500, '2023-05-01', 'Salário', '2023-05-05', 'NOT_RECEIVED', false, 12, 1, 'INCOME');

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (300.50, '2023-06-01', 'Suplementos', '2023-06-20', 'NOT_PAID', 'EXPENSE', 'IN_CASH', 0, null, 1, 5);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (120.84, '2023-06-05', 'Gasolina', '2023-06-25', 'NOT_PAID', 'EXPENSE', 'IN_CASH', 0, null, 1, 9);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (120.84, '2023-06-05', 'Colchão', '2023-06-25', 'NOT_PAID', 'EXPENSE', 'INSTALLMENT', 0, null, 1, 2);

INSERT INTO INSTALLMENT_TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, DIVISION_ID, TRANSACTION_ID,
                                    CATEGORY)
VALUES (200, '2023-06-01', 'Colchão(1/4)', '2023-06-05', 'NOT_PAID', 2, 4, 'EXPENSE');
INSERT INTO INSTALLMENT_TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, DIVISION_ID, TRANSACTION_ID,
                                    CATEGORY)
VALUES (200, '2023-06-01', 'Colchão(2/4)', '2023-07-05', 'NOT_PAID', 2, 4, 'EXPENSE');
INSERT INTO INSTALLMENT_TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, DIVISION_ID, TRANSACTION_ID,
                                    CATEGORY)
VALUES (200, '2023-06-01', 'Colchão(3/4)', '2023-08-05', 'NOT_PAID', 2, 4, 'EXPENSE');
INSERT INTO INSTALLMENT_TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, DIVISION_ID, TRANSACTION_ID,
                                    CATEGORY)
VALUES (200, '2023-06-01', 'Colchão(4/4)', '2023-09-05', 'NOT_PAID', 2, 4, 'EXPENSE');

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (60.55, '2023-05-05', 'Gasolina', '2023-05-22', 'NOT_PAID', 'EXPENSE', 'IN_CASH', 0, null, 1, 9);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (150.50, '2023-05-01', 'Suplementos', '2023-05-20', 'NOT_PAID', 'EXPENSE', 'IN_CASH', 0, null, 1, 5);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION, PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE,
                        REPEAT, CLIENT_ID, DIVISION_ID)
VALUES (1500.20, '2023-05-01', 'Processador', '2023-05-20', 'NOT_PAID', 'EXPENSE', 'IN_CASH', 0, null, 1, 3);