INSERT INTO CLIENT(NAME, EMAIL, CREATED_AT, BALANCE) VALUES ('cliente 1', 'ciente@hotmail.com', CURRENT_TIMESTAMP(), 1000);

INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (100, CURRENT_TIMESTAMP(), 'DESCRIPTION', CURRENT_TIMESTAMP() , 1, 0, 1, 0, null, 1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (150, CURRENT_TIMESTAMP(), 'DESCRIPTION', CURRENT_TIMESTAMP() , 2, 1, 2, 1, null, 1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (200, CURRENT_TIMESTAMP(), 'DESCRIPTION', CURRENT_TIMESTAMP() , 3, 1, 0, 0, 3,    1);
INSERT INTO TRANSACTION(AMOUNT, CREATED_AT, DESCRIPTION,  PAY_DAY, STATUS, CATEGORY, TRANSACTION_TYPE, FIXED_EXPENSE, REPEAT, CLIENT_ID) VALUES (100, CURRENT_TIMESTAMP(), 'DESCRIPTION', CURRENT_TIMESTAMP() , 1, 0, 0, 0, 2,    1);

INSERT INTO division(NAME, TYPE, CATEGORY, CREATED_AT) VALUES ('Academia', 'GYM', 'EXPENSE', CURRENT_TIMESTAMP()),
                                                              ('Salário', 'SALARY', 'INCOME', CURRENT_TIMESTAMP()),
                                                              ('Aluguel', 'RENT', 'EXPENSE', CURRENT_TIMESTAMP()),
                                                              ('Bônus', 'BONUS', 'INCOME', CURRENT_TIMESTAMP()),
                                                              ('Supermercado', 'MARKET', 'EXPENSE', CURRENT_TIMESTAMP()),
                                                              ('Investimento', 'INVESTMENT', 'INCOME', CURRENT_TIMESTAMP());